language: python

sudo: false

notifications:
  email: false

install:
  - pip install --upgrade tox

env:
 - TOX_ENV=py27-django16
 - TOX_ENV=py27-django17
 - TOX_ENV=py27-django18
 - TOX_ENV=py33-django16
 - TOX_ENV=py33-django17
 - TOX_ENV=py33-django18
 - TOX_ENV=py34-django16
 - TOX_ENV=py34-django17
 - TOX_ENV=py34-django18
 - TOX_ENV=pypy-django16
 - TOX_ENV=pypy-django17
 - TOX_ENV=pypy-django18

script:
  - tox -e $TOX_ENV
